name: swift_chat
description: SwiftChat - A Cross-platform AI Chat App built with Flutter
publish_to: 'none'
version: 2.6.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Theme
  cupertino_icons: ^1.0.6
  flutter_markdown: ^0.7.0
  markdown: ^7.2.0
  flutter_highlight: ^0.7.0
  flutter_math_fork: ^0.7.2
  webview_flutter: ^4.4.4  
  # State Management
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  
  # Network
  http: ^1.2.0
  dio: ^5.4.0
  
  # File & Media
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  video_player: ^2.8.2
  image: ^4.1.7
  mime: ^1.0.5
  
  # Utils
  uuid: ^4.3.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
